//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ECARulesParser.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

namespace ECARules4All.RuleEngine
{
	/// <summary>
	/// This interface defines a complete listener for a parse tree produced by
	/// <see cref="ECARulesParser"/>.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
	[System.CLSCompliant(false)]
	public interface IECARulesParserListener : IParseTreeListener
	{
		/// <summary>
		/// Enter a parse tree produced by <see cref="ECARulesParser.program"/>.
		/// </summary>
		/// <param name="context">The parse tree.</param>
		void EnterProgram([NotNull] ECARulesParser.ProgramContext context);
		/// <summary>
		/// Exit a parse tree produced by <see cref="ECARulesParser.program"/>.
		/// </summary>
		/// <param name="context">The parse tree.</param>
		void ExitProgram([NotNull] ECARulesParser.ProgramContext context);
		/// <summary>
		/// Enter a parse tree produced by <see cref="ECARulesParser.declaration"/>.
		/// </summary>
		/// <param name="context">The parse tree.</param>
		void EnterDeclaration([NotNull] ECARulesParser.DeclarationContext context);
		/// <summary>
		/// Exit a parse tree produced by <see cref="ECARulesParser.declaration"/>.
		/// </summary>
		/// <param name="context">The parse tree.</param>
		void ExitDeclaration([NotNull] ECARulesParser.DeclarationContext context);
		/// <summary>
		/// Enter a parse tree produced by <see cref="ECARulesParser.objectDeclaration"/>.
		/// </summary>
		/// <param name="context">The parse tree.</param>
		void EnterObjectDeclaration([NotNull] ECARulesParser.ObjectDeclarationContext context);
		/// <summary>
		/// Exit a parse tree produced by <see cref="ECARulesParser.objectDeclaration"/>.
		/// </summary>
		/// <param name="context">The parse tree.</param>
		void ExitObjectDeclaration([NotNull] ECARulesParser.ObjectDeclarationContext context);
		/// <summary>
		/// Enter a parse tree produced by <see cref="ECARulesParser.positionDeclaration"/>.
		/// </summary>
		/// <param name="context">The parse tree.</param>
		void EnterPositionDeclaration([NotNull] ECARulesParser.PositionDeclarationContext context);
		/// <summary>
		/// Exit a parse tree produced by <see cref="ECARulesParser.positionDeclaration"/>.
		/// </summary>
		/// <param name="context">The parse tree.</param>
		void ExitPositionDeclaration([NotNull] ECARulesParser.PositionDeclarationContext context);
		/// <summary>
		/// Enter a parse tree produced by <see cref="ECARulesParser.positionLiteral"/>.
		/// </summary>
		/// <param name="context">The parse tree.</param>
		void EnterPositionLiteral([NotNull] ECARulesParser.PositionLiteralContext context);
		/// <summary>
		/// Exit a parse tree produced by <see cref="ECARulesParser.positionLiteral"/>.
		/// </summary>
		/// <param name="context">The parse tree.</param>
		void ExitPositionLiteral([NotNull] ECARulesParser.PositionLiteralContext context);
		/// <summary>
		/// Enter a parse tree produced by <see cref="ECARulesParser.pathDeclaration"/>.
		/// </summary>
		/// <param name="context">The parse tree.</param>
		void EnterPathDeclaration([NotNull] ECARulesParser.PathDeclarationContext context);
		/// <summary>
		/// Exit a parse tree produced by <see cref="ECARulesParser.pathDeclaration"/>.
		/// </summary>
		/// <param name="context">The parse tree.</param>
		void ExitPathDeclaration([NotNull] ECARulesParser.PathDeclarationContext context);
		/// <summary>
		/// Enter a parse tree produced by <see cref="ECARulesParser.colorDeclaration"/>.
		/// </summary>
		/// <param name="context">The parse tree.</param>
		void EnterColorDeclaration([NotNull] ECARulesParser.ColorDeclarationContext context);
		/// <summary>
		/// Exit a parse tree produced by <see cref="ECARulesParser.colorDeclaration"/>.
		/// </summary>
		/// <param name="context">The parse tree.</param>
		void ExitColorDeclaration([NotNull] ECARulesParser.ColorDeclarationContext context);
		/// <summary>
		/// Enter a parse tree produced by <see cref="ECARulesParser.floatLiteral"/>.
		/// </summary>
		/// <param name="context">The parse tree.</param>
		void EnterFloatLiteral([NotNull] ECARulesParser.FloatLiteralContext context);
		/// <summary>
		/// Exit a parse tree produced by <see cref="ECARulesParser.floatLiteral"/>.
		/// </summary>
		/// <param name="context">The parse tree.</param>
		void ExitFloatLiteral([NotNull] ECARulesParser.FloatLiteralContext context);
		/// <summary>
		/// Enter a parse tree produced by <see cref="ECARulesParser.type"/>.
		/// </summary>
		/// <param name="context">The parse tree.</param>
		void EnterType([NotNull] ECARulesParser.TypeContext context);
		/// <summary>
		/// Exit a parse tree produced by <see cref="ECARulesParser.type"/>.
		/// </summary>
		/// <param name="context">The parse tree.</param>
		void ExitType([NotNull] ECARulesParser.TypeContext context);
		/// <summary>
		/// Enter a parse tree produced by <see cref="ECARulesParser.position"/>.
		/// </summary>
		/// <param name="context">The parse tree.</param>
		void EnterPosition([NotNull] ECARulesParser.PositionContext context);
		/// <summary>
		/// Exit a parse tree produced by <see cref="ECARulesParser.position"/>.
		/// </summary>
		/// <param name="context">The parse tree.</param>
		void ExitPosition([NotNull] ECARulesParser.PositionContext context);
		/// <summary>
		/// Enter a parse tree produced by <see cref="ECARulesParser.path"/>.
		/// </summary>
		/// <param name="context">The parse tree.</param>
		void EnterPath([NotNull] ECARulesParser.PathContext context);
		/// <summary>
		/// Exit a parse tree produced by <see cref="ECARulesParser.path"/>.
		/// </summary>
		/// <param name="context">The parse tree.</param>
		void ExitPath([NotNull] ECARulesParser.PathContext context);
		/// <summary>
		/// Enter a parse tree produced by <see cref="ECARulesParser.angle"/>.
		/// </summary>
		/// <param name="context">The parse tree.</param>
		void EnterAngle([NotNull] ECARulesParser.AngleContext context);
		/// <summary>
		/// Exit a parse tree produced by <see cref="ECARulesParser.angle"/>.
		/// </summary>
		/// <param name="context">The parse tree.</param>
		void ExitAngle([NotNull] ECARulesParser.AngleContext context);
		/// <summary>
		/// Enter a parse tree produced by <see cref="ECARulesParser.color"/>.
		/// </summary>
		/// <param name="context">The parse tree.</param>
		void EnterColor([NotNull] ECARulesParser.ColorContext context);
		/// <summary>
		/// Exit a parse tree produced by <see cref="ECARulesParser.color"/>.
		/// </summary>
		/// <param name="context">The parse tree.</param>
		void ExitColor([NotNull] ECARulesParser.ColorContext context);
		/// <summary>
		/// Enter a parse tree produced by <see cref="ECARulesParser.behaviourDeclaration"/>.
		/// </summary>
		/// <param name="context">The parse tree.</param>
		void EnterBehaviourDeclaration([NotNull] ECARulesParser.BehaviourDeclarationContext context);
		/// <summary>
		/// Exit a parse tree produced by <see cref="ECARulesParser.behaviourDeclaration"/>.
		/// </summary>
		/// <param name="context">The parse tree.</param>
		void ExitBehaviourDeclaration([NotNull] ECARulesParser.BehaviourDeclarationContext context);
		/// <summary>
		/// Enter a parse tree produced by <see cref="ECARulesParser.alias"/>.
		/// </summary>
		/// <param name="context">The parse tree.</param>
		void EnterAlias([NotNull] ECARulesParser.AliasContext context);
		/// <summary>
		/// Exit a parse tree produced by <see cref="ECARulesParser.alias"/>.
		/// </summary>
		/// <param name="context">The parse tree.</param>
		void ExitAlias([NotNull] ECARulesParser.AliasContext context);
		/// <summary>
		/// Enter a parse tree produced by <see cref="ECARulesParser.ecarule"/>.
		/// </summary>
		/// <param name="context">The parse tree.</param>
		void EnterEcarule([NotNull] ECARulesParser.EcaruleContext context);
		/// <summary>
		/// Exit a parse tree produced by <see cref="ECARulesParser.ecarule"/>.
		/// </summary>
		/// <param name="context">The parse tree.</param>
		void ExitEcarule([NotNull] ECARulesParser.EcaruleContext context);
		/// <summary>
		/// Enter a parse tree produced by <see cref="ECARulesParser.action"/>.
		/// </summary>
		/// <param name="context">The parse tree.</param>
		void EnterAction([NotNull] ECARulesParser.ActionContext context);
		/// <summary>
		/// Exit a parse tree produced by <see cref="ECARulesParser.action"/>.
		/// </summary>
		/// <param name="context">The parse tree.</param>
		void ExitAction([NotNull] ECARulesParser.ActionContext context);
		/// <summary>
		/// Enter a parse tree produced by <see cref="ECARulesParser.subject"/>.
		/// </summary>
		/// <param name="context">The parse tree.</param>
		void EnterSubject([NotNull] ECARulesParser.SubjectContext context);
		/// <summary>
		/// Exit a parse tree produced by <see cref="ECARulesParser.subject"/>.
		/// </summary>
		/// <param name="context">The parse tree.</param>
		void ExitSubject([NotNull] ECARulesParser.SubjectContext context);
		/// <summary>
		/// Enter a parse tree produced by <see cref="ECARulesParser.verb"/>.
		/// </summary>
		/// <param name="context">The parse tree.</param>
		void EnterVerb([NotNull] ECARulesParser.VerbContext context);
		/// <summary>
		/// Exit a parse tree produced by <see cref="ECARulesParser.verb"/>.
		/// </summary>
		/// <param name="context">The parse tree.</param>
		void ExitVerb([NotNull] ECARulesParser.VerbContext context);
		/// <summary>
		/// Enter a parse tree produced by <see cref="ECARulesParser.object"/>.
		/// </summary>
		/// <param name="context">The parse tree.</param>
		void EnterObject([NotNull] ECARulesParser.ObjectContext context);
		/// <summary>
		/// Exit a parse tree produced by <see cref="ECARulesParser.object"/>.
		/// </summary>
		/// <param name="context">The parse tree.</param>
		void ExitObject([NotNull] ECARulesParser.ObjectContext context);
		/// <summary>
		/// Enter a parse tree produced by <see cref="ECARulesParser.value"/>.
		/// </summary>
		/// <param name="context">The parse tree.</param>
		void EnterValue([NotNull] ECARulesParser.ValueContext context);
		/// <summary>
		/// Exit a parse tree produced by <see cref="ECARulesParser.value"/>.
		/// </summary>
		/// <param name="context">The parse tree.</param>
		void ExitValue([NotNull] ECARulesParser.ValueContext context);
		/// <summary>
		/// Enter a parse tree produced by <see cref="ECARulesParser.modifier"/>.
		/// </summary>
		/// <param name="context">The parse tree.</param>
		void EnterModifier([NotNull] ECARulesParser.ModifierContext context);
		/// <summary>
		/// Exit a parse tree produced by <see cref="ECARulesParser.modifier"/>.
		/// </summary>
		/// <param name="context">The parse tree.</param>
		void ExitModifier([NotNull] ECARulesParser.ModifierContext context);
		/// <summary>
		/// Enter a parse tree produced by <see cref="ECARulesParser.preposition"/>.
		/// </summary>
		/// <param name="context">The parse tree.</param>
		void EnterPreposition([NotNull] ECARulesParser.PrepositionContext context);
		/// <summary>
		/// Exit a parse tree produced by <see cref="ECARulesParser.preposition"/>.
		/// </summary>
		/// <param name="context">The parse tree.</param>
		void ExitPreposition([NotNull] ECARulesParser.PrepositionContext context);
		/// <summary>
		/// Enter a parse tree produced by <see cref="ECARulesParser.property"/>.
		/// </summary>
		/// <param name="context">The parse tree.</param>
		void EnterProperty([NotNull] ECARulesParser.PropertyContext context);
		/// <summary>
		/// Exit a parse tree produced by <see cref="ECARulesParser.property"/>.
		/// </summary>
		/// <param name="context">The parse tree.</param>
		void ExitProperty([NotNull] ECARulesParser.PropertyContext context);
		/// <summary>
		/// Enter a parse tree produced by <see cref="ECARulesParser.condition"/>.
		/// </summary>
		/// <param name="context">The parse tree.</param>
		void EnterCondition([NotNull] ECARulesParser.ConditionContext context);
		/// <summary>
		/// Exit a parse tree produced by <see cref="ECARulesParser.condition"/>.
		/// </summary>
		/// <param name="context">The parse tree.</param>
		void ExitCondition([NotNull] ECARulesParser.ConditionContext context);
		/// <summary>
		/// Enter a parse tree produced by <see cref="ECARulesParser.baseCondition"/>.
		/// </summary>
		/// <param name="context">The parse tree.</param>
		void EnterBaseCondition([NotNull] ECARulesParser.BaseConditionContext context);
		/// <summary>
		/// Exit a parse tree produced by <see cref="ECARulesParser.baseCondition"/>.
		/// </summary>
		/// <param name="context">The parse tree.</param>
		void ExitBaseCondition([NotNull] ECARulesParser.BaseConditionContext context);
		/// <summary>
		/// Enter a parse tree produced by <see cref="ECARulesParser.operator"/>.
		/// </summary>
		/// <param name="context">The parse tree.</param>
		void EnterOperator([NotNull] ECARulesParser.OperatorContext context);
		/// <summary>
		/// Exit a parse tree produced by <see cref="ECARulesParser.operator"/>.
		/// </summary>
		/// <param name="context">The parse tree.</param>
		void ExitOperator([NotNull] ECARulesParser.OperatorContext context);
	}
}