//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ECARulesParser.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

namespace EcaRules
{
	/// <summary>
	/// This class provides an empty implementation of <see cref="IECARulesParserListener"/>,
	/// which can be extended to create a listener which only needs to handle a subset
	/// of the available methods.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
	[System.CLSCompliant(false)]
	public partial class ECARulesParserBaseListener : IECARulesParserListener
	{
		/// <summary>
		/// Enter a parse tree produced by <see cref="ECARulesParser.program"/>.
		/// <para>The default implementation does nothing.</para>
		/// </summary>
		/// <param name="context">The parse tree.</param>
		public virtual void EnterProgram([NotNull] ECARulesParser.ProgramContext context) { }
		/// <summary>
		/// Exit a parse tree produced by <see cref="ECARulesParser.program"/>.
		/// <para>The default implementation does nothing.</para>
		/// </summary>
		/// <param name="context">The parse tree.</param>
		public virtual void ExitProgram([NotNull] ECARulesParser.ProgramContext context) { }
		/// <summary>
		/// Enter a parse tree produced by <see cref="ECARulesParser.declaration"/>.
		/// <para>The default implementation does nothing.</para>
		/// </summary>
		/// <param name="context">The parse tree.</param>
		public virtual void EnterDeclaration([NotNull] ECARulesParser.DeclarationContext context) { }
		/// <summary>
		/// Exit a parse tree produced by <see cref="ECARulesParser.declaration"/>.
		/// <para>The default implementation does nothing.</para>
		/// </summary>
		/// <param name="context">The parse tree.</param>
		public virtual void ExitDeclaration([NotNull] ECARulesParser.DeclarationContext context) { }
		/// <summary>
		/// Enter a parse tree produced by <see cref="ECARulesParser.objectDeclaration"/>.
		/// <para>The default implementation does nothing.</para>
		/// </summary>
		/// <param name="context">The parse tree.</param>
		public virtual void EnterObjectDeclaration([NotNull] ECARulesParser.ObjectDeclarationContext context) { }
		/// <summary>
		/// Exit a parse tree produced by <see cref="ECARulesParser.objectDeclaration"/>.
		/// <para>The default implementation does nothing.</para>
		/// </summary>
		/// <param name="context">The parse tree.</param>
		public virtual void ExitObjectDeclaration([NotNull] ECARulesParser.ObjectDeclarationContext context) { }
		/// <summary>
		/// Enter a parse tree produced by <see cref="ECARulesParser.positionDeclaration"/>.
		/// <para>The default implementation does nothing.</para>
		/// </summary>
		/// <param name="context">The parse tree.</param>
		public virtual void EnterPositionDeclaration([NotNull] ECARulesParser.PositionDeclarationContext context) { }
		/// <summary>
		/// Exit a parse tree produced by <see cref="ECARulesParser.positionDeclaration"/>.
		/// <para>The default implementation does nothing.</para>
		/// </summary>
		/// <param name="context">The parse tree.</param>
		public virtual void ExitPositionDeclaration([NotNull] ECARulesParser.PositionDeclarationContext context) { }
		/// <summary>
		/// Enter a parse tree produced by <see cref="ECARulesParser.positionLiteral"/>.
		/// <para>The default implementation does nothing.</para>
		/// </summary>
		/// <param name="context">The parse tree.</param>
		public virtual void EnterPositionLiteral([NotNull] ECARulesParser.PositionLiteralContext context) { }
		/// <summary>
		/// Exit a parse tree produced by <see cref="ECARulesParser.positionLiteral"/>.
		/// <para>The default implementation does nothing.</para>
		/// </summary>
		/// <param name="context">The parse tree.</param>
		public virtual void ExitPositionLiteral([NotNull] ECARulesParser.PositionLiteralContext context) { }
		/// <summary>
		/// Enter a parse tree produced by <see cref="ECARulesParser.pathDeclaration"/>.
		/// <para>The default implementation does nothing.</para>
		/// </summary>
		/// <param name="context">The parse tree.</param>
		public virtual void EnterPathDeclaration([NotNull] ECARulesParser.PathDeclarationContext context) { }
		/// <summary>
		/// Exit a parse tree produced by <see cref="ECARulesParser.pathDeclaration"/>.
		/// <para>The default implementation does nothing.</para>
		/// </summary>
		/// <param name="context">The parse tree.</param>
		public virtual void ExitPathDeclaration([NotNull] ECARulesParser.PathDeclarationContext context) { }
		/// <summary>
		/// Enter a parse tree produced by <see cref="ECARulesParser.colorDeclaration"/>.
		/// <para>The default implementation does nothing.</para>
		/// </summary>
		/// <param name="context">The parse tree.</param>
		public virtual void EnterColorDeclaration([NotNull] ECARulesParser.ColorDeclarationContext context) { }
		/// <summary>
		/// Exit a parse tree produced by <see cref="ECARulesParser.colorDeclaration"/>.
		/// <para>The default implementation does nothing.</para>
		/// </summary>
		/// <param name="context">The parse tree.</param>
		public virtual void ExitColorDeclaration([NotNull] ECARulesParser.ColorDeclarationContext context) { }
		/// <summary>
		/// Enter a parse tree produced by <see cref="ECARulesParser.floatLiteral"/>.
		/// <para>The default implementation does nothing.</para>
		/// </summary>
		/// <param name="context">The parse tree.</param>
		public virtual void EnterFloatLiteral([NotNull] ECARulesParser.FloatLiteralContext context) { }
		/// <summary>
		/// Exit a parse tree produced by <see cref="ECARulesParser.floatLiteral"/>.
		/// <para>The default implementation does nothing.</para>
		/// </summary>
		/// <param name="context">The parse tree.</param>
		public virtual void ExitFloatLiteral([NotNull] ECARulesParser.FloatLiteralContext context) { }
		/// <summary>
		/// Enter a parse tree produced by <see cref="ECARulesParser.type"/>.
		/// <para>The default implementation does nothing.</para>
		/// </summary>
		/// <param name="context">The parse tree.</param>
		public virtual void EnterType([NotNull] ECARulesParser.TypeContext context) { }
		/// <summary>
		/// Exit a parse tree produced by <see cref="ECARulesParser.type"/>.
		/// <para>The default implementation does nothing.</para>
		/// </summary>
		/// <param name="context">The parse tree.</param>
		public virtual void ExitType([NotNull] ECARulesParser.TypeContext context) { }
		/// <summary>
		/// Enter a parse tree produced by <see cref="ECARulesParser.position"/>.
		/// <para>The default implementation does nothing.</para>
		/// </summary>
		/// <param name="context">The parse tree.</param>
		public virtual void EnterPosition([NotNull] ECARulesParser.PositionContext context) { }
		/// <summary>
		/// Exit a parse tree produced by <see cref="ECARulesParser.position"/>.
		/// <para>The default implementation does nothing.</para>
		/// </summary>
		/// <param name="context">The parse tree.</param>
		public virtual void ExitPosition([NotNull] ECARulesParser.PositionContext context) { }
		/// <summary>
		/// Enter a parse tree produced by <see cref="ECARulesParser.path"/>.
		/// <para>The default implementation does nothing.</para>
		/// </summary>
		/// <param name="context">The parse tree.</param>
		public virtual void EnterPath([NotNull] ECARulesParser.PathContext context) { }
		/// <summary>
		/// Exit a parse tree produced by <see cref="ECARulesParser.path"/>.
		/// <para>The default implementation does nothing.</para>
		/// </summary>
		/// <param name="context">The parse tree.</param>
		public virtual void ExitPath([NotNull] ECARulesParser.PathContext context) { }
		/// <summary>
		/// Enter a parse tree produced by <see cref="ECARulesParser.angle"/>.
		/// <para>The default implementation does nothing.</para>
		/// </summary>
		/// <param name="context">The parse tree.</param>
		public virtual void EnterAngle([NotNull] ECARulesParser.AngleContext context) { }
		/// <summary>
		/// Exit a parse tree produced by <see cref="ECARulesParser.angle"/>.
		/// <para>The default implementation does nothing.</para>
		/// </summary>
		/// <param name="context">The parse tree.</param>
		public virtual void ExitAngle([NotNull] ECARulesParser.AngleContext context) { }
		/// <summary>
		/// Enter a parse tree produced by <see cref="ECARulesParser.color"/>.
		/// <para>The default implementation does nothing.</para>
		/// </summary>
		/// <param name="context">The parse tree.</param>
		public virtual void EnterColor([NotNull] ECARulesParser.ColorContext context) { }
		/// <summary>
		/// Exit a parse tree produced by <see cref="ECARulesParser.color"/>.
		/// <para>The default implementation does nothing.</para>
		/// </summary>
		/// <param name="context">The parse tree.</param>
		public virtual void ExitColor([NotNull] ECARulesParser.ColorContext context) { }
		/// <summary>
		/// Enter a parse tree produced by <see cref="ECARulesParser.behaviourDeclaration"/>.
		/// <para>The default implementation does nothing.</para>
		/// </summary>
		/// <param name="context">The parse tree.</param>
		public virtual void EnterBehaviourDeclaration([NotNull] ECARulesParser.BehaviourDeclarationContext context) { }
		/// <summary>
		/// Exit a parse tree produced by <see cref="ECARulesParser.behaviourDeclaration"/>.
		/// <para>The default implementation does nothing.</para>
		/// </summary>
		/// <param name="context">The parse tree.</param>
		public virtual void ExitBehaviourDeclaration([NotNull] ECARulesParser.BehaviourDeclarationContext context) { }
		/// <summary>
		/// Enter a parse tree produced by <see cref="ECARulesParser.alias"/>.
		/// <para>The default implementation does nothing.</para>
		/// </summary>
		/// <param name="context">The parse tree.</param>
		public virtual void EnterAlias([NotNull] ECARulesParser.AliasContext context) { }
		/// <summary>
		/// Exit a parse tree produced by <see cref="ECARulesParser.alias"/>.
		/// <para>The default implementation does nothing.</para>
		/// </summary>
		/// <param name="context">The parse tree.</param>
		public virtual void ExitAlias([NotNull] ECARulesParser.AliasContext context) { }
		/// <summary>
		/// Enter a parse tree produced by <see cref="ECARulesParser.ecarule"/>.
		/// <para>The default implementation does nothing.</para>
		/// </summary>
		/// <param name="context">The parse tree.</param>
		public virtual void EnterEcarule([NotNull] ECARulesParser.EcaruleContext context) { }
		/// <summary>
		/// Exit a parse tree produced by <see cref="ECARulesParser.ecarule"/>.
		/// <para>The default implementation does nothing.</para>
		/// </summary>
		/// <param name="context">The parse tree.</param>
		public virtual void ExitEcarule([NotNull] ECARulesParser.EcaruleContext context) { }
		/// <summary>
		/// Enter a parse tree produced by <see cref="ECARulesParser.action"/>.
		/// <para>The default implementation does nothing.</para>
		/// </summary>
		/// <param name="context">The parse tree.</param>
		public virtual void EnterAction([NotNull] ECARulesParser.ActionContext context) { }
		/// <summary>
		/// Exit a parse tree produced by <see cref="ECARulesParser.action"/>.
		/// <para>The default implementation does nothing.</para>
		/// </summary>
		/// <param name="context">The parse tree.</param>
		public virtual void ExitAction([NotNull] ECARulesParser.ActionContext context) { }
		/// <summary>
		/// Enter a parse tree produced by <see cref="ECARulesParser.subject"/>.
		/// <para>The default implementation does nothing.</para>
		/// </summary>
		/// <param name="context">The parse tree.</param>
		public virtual void EnterSubject([NotNull] ECARulesParser.SubjectContext context) { }
		/// <summary>
		/// Exit a parse tree produced by <see cref="ECARulesParser.subject"/>.
		/// <para>The default implementation does nothing.</para>
		/// </summary>
		/// <param name="context">The parse tree.</param>
		public virtual void ExitSubject([NotNull] ECARulesParser.SubjectContext context) { }
		/// <summary>
		/// Enter a parse tree produced by <see cref="ECARulesParser.verb"/>.
		/// <para>The default implementation does nothing.</para>
		/// </summary>
		/// <param name="context">The parse tree.</param>
		public virtual void EnterVerb([NotNull] ECARulesParser.VerbContext context) { }
		/// <summary>
		/// Exit a parse tree produced by <see cref="ECARulesParser.verb"/>.
		/// <para>The default implementation does nothing.</para>
		/// </summary>
		/// <param name="context">The parse tree.</param>
		public virtual void ExitVerb([NotNull] ECARulesParser.VerbContext context) { }
		/// <summary>
		/// Enter a parse tree produced by <see cref="ECARulesParser.object"/>.
		/// <para>The default implementation does nothing.</para>
		/// </summary>
		/// <param name="context">The parse tree.</param>
		public virtual void EnterObject([NotNull] ECARulesParser.ObjectContext context) { }
		/// <summary>
		/// Exit a parse tree produced by <see cref="ECARulesParser.object"/>.
		/// <para>The default implementation does nothing.</para>
		/// </summary>
		/// <param name="context">The parse tree.</param>
		public virtual void ExitObject([NotNull] ECARulesParser.ObjectContext context) { }
		/// <summary>
		/// Enter a parse tree produced by <see cref="ECARulesParser.value"/>.
		/// <para>The default implementation does nothing.</para>
		/// </summary>
		/// <param name="context">The parse tree.</param>
		public virtual void EnterValue([NotNull] ECARulesParser.ValueContext context) { }
		/// <summary>
		/// Exit a parse tree produced by <see cref="ECARulesParser.value"/>.
		/// <para>The default implementation does nothing.</para>
		/// </summary>
		/// <param name="context">The parse tree.</param>
		public virtual void ExitValue([NotNull] ECARulesParser.ValueContext context) { }
		/// <summary>
		/// Enter a parse tree produced by <see cref="ECARulesParser.modifier"/>.
		/// <para>The default implementation does nothing.</para>
		/// </summary>
		/// <param name="context">The parse tree.</param>
		public virtual void EnterModifier([NotNull] ECARulesParser.ModifierContext context) { }
		/// <summary>
		/// Exit a parse tree produced by <see cref="ECARulesParser.modifier"/>.
		/// <para>The default implementation does nothing.</para>
		/// </summary>
		/// <param name="context">The parse tree.</param>
		public virtual void ExitModifier([NotNull] ECARulesParser.ModifierContext context) { }
		/// <summary>
		/// Enter a parse tree produced by <see cref="ECARulesParser.preposition"/>.
		/// <para>The default implementation does nothing.</para>
		/// </summary>
		/// <param name="context">The parse tree.</param>
		public virtual void EnterPreposition([NotNull] ECARulesParser.PrepositionContext context) { }
		/// <summary>
		/// Exit a parse tree produced by <see cref="ECARulesParser.preposition"/>.
		/// <para>The default implementation does nothing.</para>
		/// </summary>
		/// <param name="context">The parse tree.</param>
		public virtual void ExitPreposition([NotNull] ECARulesParser.PrepositionContext context) { }
		/// <summary>
		/// Enter a parse tree produced by <see cref="ECARulesParser.property"/>.
		/// <para>The default implementation does nothing.</para>
		/// </summary>
		/// <param name="context">The parse tree.</param>
		public virtual void EnterProperty([NotNull] ECARulesParser.PropertyContext context) { }
		/// <summary>
		/// Exit a parse tree produced by <see cref="ECARulesParser.property"/>.
		/// <para>The default implementation does nothing.</para>
		/// </summary>
		/// <param name="context">The parse tree.</param>
		public virtual void ExitProperty([NotNull] ECARulesParser.PropertyContext context) { }
		/// <summary>
		/// Enter a parse tree produced by <see cref="ECARulesParser.condition"/>.
		/// <para>The default implementation does nothing.</para>
		/// </summary>
		/// <param name="context">The parse tree.</param>
		public virtual void EnterCondition([NotNull] ECARulesParser.ConditionContext context) { }
		/// <summary>
		/// Exit a parse tree produced by <see cref="ECARulesParser.condition"/>.
		/// <para>The default implementation does nothing.</para>
		/// </summary>
		/// <param name="context">The parse tree.</param>
		public virtual void ExitCondition([NotNull] ECARulesParser.ConditionContext context) { }
		/// <summary>
		/// Enter a parse tree produced by <see cref="ECARulesParser.baseCondition"/>.
		/// <para>The default implementation does nothing.</para>
		/// </summary>
		/// <param name="context">The parse tree.</param>
		public virtual void EnterBaseCondition([NotNull] ECARulesParser.BaseConditionContext context) { }
		/// <summary>
		/// Exit a parse tree produced by <see cref="ECARulesParser.baseCondition"/>.
		/// <para>The default implementation does nothing.</para>
		/// </summary>
		/// <param name="context">The parse tree.</param>
		public virtual void ExitBaseCondition([NotNull] ECARulesParser.BaseConditionContext context) { }
		/// <summary>
		/// Enter a parse tree produced by <see cref="ECARulesParser.operator"/>.
		/// <para>The default implementation does nothing.</para>
		/// </summary>
		/// <param name="context">The parse tree.</param>
		public virtual void EnterOperator([NotNull] ECARulesParser.OperatorContext context) { }
		/// <summary>
		/// Exit a parse tree produced by <see cref="ECARulesParser.operator"/>.
		/// <para>The default implementation does nothing.</para>
		/// </summary>
		/// <param name="context">The parse tree.</param>
		public virtual void ExitOperator([NotNull] ECARulesParser.OperatorContext context) { }

		/// <inheritdoc/>
		/// <remarks>The default implementation does nothing.</remarks>
		public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
		/// <inheritdoc/>
		/// <remarks>The default implementation does nothing.</remarks>
		public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
		/// <inheritdoc/>
		/// <remarks>The default implementation does nothing.</remarks>
		public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
		/// <inheritdoc/>
		/// <remarks>The default implementation does nothing.</remarks>
		public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
	}
}